services:
  - type: web
    name: gbt-miner-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: RPC_URL
        value: https://gbtnetwork-render.onrender.com
      - key: CONTRACT_ADDRESS
        value: 0x0000000000000000000000000000000000000000
      - key: PRIVATE_KEY
        value: your_private_key_here
      - key: ACCOUNT
        value: your_account_address_here
