services:
  - type: web
    name: gbt-hardhat-pow
    runtime: node
    buildCommand: npm install
    startCommand: bash render.deploy
    envVars:
      - key: RPC_URL
        value: https://gbtnetwork-render.onrender.com
      - key: PRIVATE_KEY
        sync: false   # set in dashboard (do not commit)
